# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a31a361cca3c65236344b635964be50df7e3eb7977c098675ccab25014840da8869902e35111d9066837e2b6e1f60cdc73c6cc1ff001b4889f024c584d51fd2

test:
  secret_key_base: 91edd2c0879463f55f383058aaa36d2a61eba7b5da0596ed4b5c5ba12704a988eb322e2ae6879d0630e37bbfaf26bf2c6fe158285e731b48f5ad7a5b35523bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
